### ISSUE TITLE
Crash when right-clicking pebble off the ground

### ISSUE THREAD

**Issue by SilearFlare** [CanisArtorus/ProspectorJournal#10]
Here's the log:

> Time: 10/18/21 10:48 PM
> Description: Exception in server tick loop
> 
> java.lang.NoClassDefFoundError: gregtech.tileentity.misc.MultiTileEntityRock
> 	at com.github.canisartorus.prospectorjournal.JournalBehaviour.lookForSample(JournalBehaviour.java:60)
> 	at com.github.canisartorus.prospectorjournal.RightClickEvent.playerRightClick(RightClickEvent.java:30)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_495_RightClickEvent_playerRightClick_PlayerInteractEvent.invoke(.dynamic)
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
> 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
> 	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
> 	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:353)
> 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
> 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
> 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> Caused by: java.lang.ClassNotFoundException: gregtech.tileentity.misc.MultiTileEntityRock
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
> 	... 17 more
> Caused by: java.lang.NullPointerException
> 	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
> 	at sereneseasons.asm.transformer.WeatherTransformer.transform(WeatherTransformer.java:21)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
> 	... 20 more

Thanks in advance for any help with this issue!

**Comment by CanisArtorus** [comment]
Which version of Gregtech are you using?

I've just discovered the 6.14.21 pre-release secret versions have changed package structure for that class, and will not be compatible.

**Comment by SilearFlare** [comment]
Oh yeah, that would explain it, I'm using one of the latest secret versions.
Thanks for the quick reply!

**Comment by SilearFlare** [comment]
Hate to be a bother again, the game doesn't seem to be able to find the latest public release of gregtech 6 (6.14.21) when it is installed, even if it's set as a dependency.
![Screenshot from 2021-10-21 13-07-42](https://user-images.githubusercontent.com/5557920/138265625-c85b1bfc-687e-45d1-bc6e-0eb3ecf1bc90.png)

**Comment by CanisArtorus** [comment]
[.. , ..) is "set notation", prior fix was to reject versions of Gregtech 6.14.21 and higher.
The version PJ 0.12 that is compatible with just-released GT will be along today.

**Comment by SilearFlare** [comment]
Yeah sorry to just keep re-opening, but it's still doing the thing.
![Screenshot from 2021-10-22 07-42-13](https://user-images.githubusercontent.com/5557920/138399449-1347192e-ca49-47d4-9fca-607507ddb3cf.png)
.
